### ISSUE TITLE
How to determine if decoded frames make sense

### ISSUE THREAD

**Issue by janvgils** [daniestevez/gr-satellites#198]
We have a decoded frame, but does it make sense ?

Today there was a message that there was an unknown satellite transmitting on 437.600 MHz.

After some orbital investigations and comparison there is a big change that it is BY70-3 with ID 46839, the strange is, that it is using 437.600 and not the IARU coordinated frequency 437.443 `http://www.amsatuk.me.uk/iaru/finished_detail.php?serialnum=726`

Lets say this is indeed BY70-3, so take the latest BY satyaml file and use it as a template for BY70-3, this provides the following:

```
name: BY70-3
norad: 46839
data:
  &tlm Telemetry:
    telemetry: by02
  &codec2 Codec2:
    decoder: codec2_udp_sink
transmitters:
  9k6 BPSK downlink:
    frequency: 436.600e+6
    modulation: BPSK
    baudrate: 9600
    framing: LilacSat-1
    data:
    - *tlm
    additional_data:
      codec2: *codec2
```

Using the below cli command it generates the following decodes:

```
gr_satellites 46839 --wavfile BY70-3_satnogs_3197706_2020-11-25T15-57-05.wav --samp_rate 48e3
```
```
-> Packet from 9k6 BPSK downlink
Container: 
    header = Container: 
        transfer_frame_version_number = 2
        spacecraft_id = 520
        virtual_channel_id = 5
        ocf_flag = False
        master_channel_frame_count = 207
        virtual_channel_frame_count = 196
        first_header_pointer = 120
    padding = b"\xd5\x89\xff\x1e\xd2\xa9)\x9e<\xc0\xf5>q\xc7<\xe2\x03\xef\xca\x82D\x80\xfc\xf0.u\x0f,ka\x84%\x97F,\xeb\xb1\x15v\xdde\x1c)\xdf\xb1\xb8\xa2\x94\xe8)\xee\xd7\x85\xc1\x08\x9e\xaeR\x8c3\xf8b\xc2\xaev\x03\x0eS\xb9\x85'0+\xdf\xad\xdc" (total 76)
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 285767
```

```
* MESSAGE DEBUG PRINT PDU VERBOSE *
((transmitter . 9k6 BPSK downlink))
pdu_length = 81
contents = 
0000: a0 8a cf c4 78 d5 89 ff 1e d2 a9 29 9e 3c c0 f5 
0010: 3e 71 c7 3c e2 03 ef ca 82 44 80 fc f0 2e 75 0f 
0020: 2c 6b 61 84 25 97 46 2c eb b1 15 76 dd 65 1c 29 
0030: df b1 b8 a2 94 e8 29 ee d7 85 c1 08 9e ae 52 8c 
0040: 33 f8 62 c2 ae 76 03 0e 53 b9 85 27 30 2b df ad 
0050: dc 
***********************************
```

It is all looking pretty wel, but is this a good assumption ?

Are there some ways to do basic sanity checks, so you know you are on the right track?

Regards, Jan PE0SAT
