### ISSUE TITLE
One satellite multiple downlink frequencies

### ISSUE THREAD

**Issue by janvgils** [daniestevez/gr-satellites#271]
In this specific case I am using UWE-3 as an example, this satellite and also others that are build by the [Uni Würzburg](https://www.informatik.uni-wuerzburg.de/space/forschung/space-exploration/projects/) use FSK AX.25 G3RUH but have multiple downlink frequencies.

Would it make sense to configure them all in the `UWE-3.yml` file?

```
name: UWE-3
norad: 39446
data:
  &tlm Telemetry:
    telemetry: ax25
transmitters:
  1k2 AFSK downlink:
    frequency: 437.385e+6
    modulation: AFSK
    baudrate: 1200
    af_carrier: 1700
    deviation: 500
    framing: AX.25
    data:
    - *tlm
  9k6 FSK downlink 1:
    frequency: 435.000e+6
    modulation: FSK
    baudrate: 9600
    framing: AX.25 G3RUH
    data:
    - *tlm
  9k6 FSK downlink 2:
    frequency: 436.395e+6
    modulation: FSK
    baudrate: 9600
    framing: AX.25 G3RUH
    data:
    - *tlm
  9k6 FSK downlink 3:
    frequency: 437.385e+6
    modulation: FSK
    baudrate: 9600
    framing: AX.25 G3RUH
    data:
    - *tlm
```
