### ISSUE TITLE
MIR-SAT1 missing in maint-3.8 branch

### ISSUE THREAD

**Issue by janvgils** [daniestevez/gr-satellites#272]
Good evening Daniel,

This evening after reading an email on the AMSAT-BB I saw that MIR-SAT1 should be supported by gr-satellites.
After pulling the last updates (I am on branch 3.8, because I have no GNURadio 3.9 support yet on Debian bullseye) I saw that the MIR-SAT yaml file wasn't being pulled in.

So I did some searches and saw that it was part of the master branch and created the file manually, this went fine and `gr_satellites --list_satellites` did show MIR-SAT1.

```
* MIR-SAT1 (NORAD 90001)
    9k6 FSK downlink 436.925 MHz FSK AX.25 G3RUH
```

I do wonder, what is the function of the `&file` option?

```
ame: MIR-SAT1
norad: 90001
data:
  &tlm Telemetry:
    telemetry: mirsat1
  &file Files:
    files: mirsat1
transmitters:
  9k6 FSK downlink:
    frequency: 436.925e+6
    modulation: FSK
    baudrate: 9600
    framing: AX.25 G3RUH
    data:
    - *tlm
    - *file
```

I hope it is possible to make MIR-SAT1 available in maint-3.8.
