### ISSUE TITLE
Strange TUBIN Mobitex-NX decodes

### ISSUE THREAD

**Issue by janvgils** [daniestevez/gr-satellites#283]
Good evening,

I tried to decode the signals from TUBIN on both gr-satellites master and maint-3.8.
Master isn't working because the Mobitex-NX OOT module source isn't migrated to GNURadio 3.9.

When I try to decode the signals with a maint-3.8 installation and using the following Yaml file I also ran in to issues.

```
name: TUBIN
norad: 99678
data:
  &tlm Telemetry:
    unknown
transmitters:
  1k2 FSK downlink:
    frequency: 435.950e+6
    modulation: FSK
    baudrate: 1200
    framing: Mobitex-NX
    data:
    - *tlm
  2k4 FSK downlink:
    frequency: 435.950e+6
    modulation: FSK
    baudrate: 2400
    framing: Mobitex-NX
    data:
    - *tlm
  4k8 FSK downlink:
    frequency: 435.950e+6
    modulation: FSK
    baudrate: 4800
    framing: Mobitex-NX
    data:
    - *tlm
  9k6 FSK downlink:
    frequency: 435.950e+6
    modulation: FSK
    baudrate: 4800
    framing: Mobitex-NX
    data:
    - *tlm
```

Decode example:

```
# Decoding Satellite 99678.
* MESSAGE DEBUG PRINT PDU VERBOSE *
((transmitter . 4k8 FSK downlink) . 5)
pdu_length = 0
contents = 
***********************************
Error while submitting telemetry: HTTP Error 400: Bad Request
* MESSAGE DEBUG PRINT PDU VERBOSE *
((transmitter . 9k6 FSK downlink) . 5)
pdu_length = 0
contents = 
***********************************
Error while submitting telemetry: HTTP Error 400: Bad Request
* MESSAGE DEBUG PRINT PDU VERBOSE *
((transmitter . 9k6 FSK downlink) . 5)
pdu_length = 0
contents =
```

```
***********************************
Error while submitting telemetry: HTTP Error 400: Bad Request
* MESSAGE DEBUG PRINT PDU VERBOSE *
((transmitter . 1k2 FSK downlink) . 1)
pdu_length = 520
contents = 
0000: 3b f1 58 64 2e 0c 3f f7 f6 80 39 c8 b0 d6 d5 f3 
0010: 84 93 91 07 20 b9 fd 68 32 16 ec 6a b8 86 2b 1b 
0020: b1 9f 17 43 10 e2 56 6e 2c be d7 70 af 11 9c e6 
0030: 02 c5 28 d7 18 bc 6a d9 57 97 32 c7 c4 ce 61 37 
0040: 86 12 9f 2b 20 73 07 78 51 b8 68 14 50 58 85 9b 
0050: c4 90 9a 65 b7 79 75 d4 85 58 4d ec 49 ee 99 e2 
0060: fe d0 75 d8 1c 6a 69 bc 4b 64 76 88 7a 8f 0b 38 
0070: a9 66 34 3d 42 33 8b c7 6c 51 27 1e 39 b0 53 21 
0080: bb 0a 04 5f 67 a8 2e 6d cb 98 82 28 eb b2 94 df 
0090: 77 02 2b 50 b3 b4 dc 34 be 07 f3 5d 4e 55 25 2f 
00a0: aa 61 ac 01 3c 60 2d c3 64 12 e4 c6 e6 ba f2 d4 
00b0: 7e 93 7b 17 01 2a 7e 4e 94 c6 4e 8f 0a f7 ed 08 
00c0: c4 dc cf 0c ef 2c 3c 38 3d 5a 3d f3 d2 5e 28 f0 
00d0: a9 29 09 39 12 75 70 06 0c 63 a1 d8 f4 15 da 96 
00e0: 29 96 f5 7d f6 77 05 33 93 05 e7 0e 2d 72 7a d4 
00f0: de e5 82 ab 6d 95 b9 d8 30 11 9a 1f c0 39 b5 dc 
0100: 52 ac 71 ab b3 9a 29 8a 94 6c 69 4e 14 6b a8 0b 
0110: 4c 4e d5 46 f3 11 15 73 0b be 4a b4 05 60 3a 39 
0120: 24 c3 21 6b 2f 8c 4c 15 0a 25 13 3b 99 07 f8 71 
0130: a5 01 84 a8 14 80 a8 6c 15 be 33 cc cb a2 8b 02 
0140: f8 5a 8c dd 3a bd 8b 42 18 4c 60 f3 13 29 d7 a1 
0150: da 5b b3 ae 92 e2 f2 41 89 79 e3 46 1c c8 8f a4 
0160: d4 e7 ae 39 4c 49 8f 62 1c c8 ea 44 45 4a df 9d 
0170: c2 59 44 74 1a 43 39 e0 2d f8 3b b3 60 66 fd 3b 
0180: 4b 18 62 88 2c a2 96 96 45 bc b5 ad 82 fb f0 4b 
0190: da 6b ed 6f 3d 38 2f 94 28 e0 69 ea 9e 9b 98 3a 
01a0: 90 a2 a6 d8 66 8a 65 71 db da a3 e5 4a 2f 79 91 
01b0: d4 fa 6e f9 5a bd af 26 b6 c6 65 75 6b 9b 47 62 
01c0: 67 9f 98 bc f0 01 3d fb 2c 9b 54 0e f0 5b 78 dd 
01d0: ea 0e 51 a2 27 fd 70 75 56 83 87 1e 34 42 0f f5 
01e0: 7e 14 45 a9 07 c5 29 68 cb 45 6f 9f ff 30 c2 57 
01f0: 43 38 26 7e 1c 43 cc 8a 03 82 de f3 07 4e a8 87 
0200: 3b 2a aa ff ff ff 0f bb
```

Maybe if time allows it, you can have a look.

Observation used: https://network.satnogs.org/observations/4351767/
